version: 2
registries:
  pip-github:
    type: python-index
    url: https://movandi.github.io/pypi_server/
    replaces-base: true
updates:
  - package-ecosystem: "pip"
    registries:
    - pip-github
    directory: "/"
    schedule:
        interval: "daily"
    insecure-external-code-execution: allow
